implement Building design reports page and Building design structure page.
RustedMiind/VD-Dashboard-React pull request #89
Opened 2024-01-29 16:43 UTC by SallamRady

2024-01-29 16:56 UTC, RustedMiind requested changes

2024-01-29 16:56 UTC, RustedMiind commented on src/pages/DesignReports/AddDesign.tsx
Replace States with react-hook-form
Replace style prop to sx

2024-01-29 16:56 UTC, RustedMiind commented on src/pages/DesignReports/components/ClassificationCardContainer/ClassificationCardContainer.tsx
Replace style prop to sx

2024-01-29 16:56 UTC, RustedMiind commented on src/pages/DesignReports/components/Table/Table.tsx
Replace style prop to sx

2024-01-29 16:56 UTC, RustedMiind commented on src/pages/DesignReports/components/classificationCard/ClassificationCard.tsx
Replace style prop to sx

2024-01-29 18:39 UTC, RustedMiind approved these changes

2024-01-31 14:00 UTC, SallamRady commented on src/pages/DesignReports/components/ClassificationCardContainer/ClassificationCardContainer.tsx
done

2024-01-31 20:59 UTC, closed without merging